{{ if .Values.input006 }}
{{ if .Values.input003 }}
{{ if .Values.input004 }}
{{ if .Values.input002 }}
{{ if .Values.input005 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-011-state
data:
  constant: unchanged

{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
