{{ if .Values.input004 }}
{{ if .Values.input003 }}
{{ if .Values.input002 }}
{{ if .Values.input008 }}
{{ if .Values.input007 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-000-state
data:
  coupled: "{{ .Values.input008 }}"

{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
