apiVersion: v1
kind: Service
metadata:
  name: case-service
spec:
  ports:
    - port: {{ if .Values.input002 }}8080{{ else }}80{{ end }}
      targetPort: {{ if .Values.input002 }}8080{{ else }}80{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: case-ingress
spec:
  defaultBackend:
    service:
      name: case-service
      port:
        number: {{ if .Values.input002 }}8080{{ else }}80{{ end }}
