apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  value: "{{ if .Values.featureEnabled }}{{ if .Values.backendEnabled }}1.150349{{ else }}-0.318639{{ end }}{{ else }}{{ if .Values.backendEnabled }}0.318639{{ else }}-1.150349{{ end }}{{ end }}"
