apiVersion: v1
kind: ConfigMap
metadata:
  name: case-state
data:
  base: present
{{ if .Values.input002 }}{{ if .Values.input003 }}{{ if .Values.input004 }}{{ if .Values.input005 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: case-rare
data:
  region: rare
{{ end }}{{ end }}{{ end }}{{ end }}
