apiVersion: v1
kind: ConfigMap
metadata:
  name: component-007-state
data:
  base: present
{{ if .Values.input006 }}{{ if .Values.input002 }}{{ if .Values.input007 }}{{ if .Values.input004 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-007-rare
data:
  region: rare
{{ end }}{{ end }}{{ end }}{{ end }}
