apiVersion: v1
kind: Service
metadata:
  name: component-005-service
spec:
  ports:
    - port: {{ if .Values.input003 }}8080{{ else }}80{{ end }}
      targetPort: {{ if .Values.input003 }}8080{{ else }}80{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: component-005-ingress
spec:
  defaultBackend:
    service:
      name: component-005-service
      port:
        number: {{ if .Values.input003 }}8080{{ else }}80{{ end }}
