"""
Check explicit rejection contracts against native Helm and opaque template boundaries.
"""

import json
import shutil
from pathlib import Path
from textwrap import dedent

import pytest
from hypothesis import strategies as st

from hypothesis_helm.charts import yamlio
from hypothesis_helm.charts.runner import Chart, RenderFailure, check_chart, render
from hypothesis_helm.compiler.asts.contracts import Contracts, calls, expression
from hypothesis_helm.compiler.asts.templates import lower, walk
from hypothesis_helm.compiler.passes.rejections import matches_rejection
from hypothesis_helm.reporting.repository import write_reports
from hypothesis_helm.schemas.contracts import mapping


@pytest.fixture
def guarded_chart(tmp_path: Path) -> Chart:
    """
    Create an aggregated helper validator resembling Cassandra's TLS requirement.

    Args:
        tmp_path (Path): Isolated chart directory.

    Returns:
        Chart: Chart with valid defaults, helper-based rejection, and a conditional required field.
    """
    (tmp_path / "templates").mkdir()
    (tmp_path / "Chart.yaml").write_text(
        dedent("""
        apiVersion: v2
        name: guarded
        version: 1.0.0
    """)
    )
    defaults = {"tls": {"mode": "none", "autoGenerated": False, "secret": ""}, "name": "example", "count": 1}
    (tmp_path / "values.yaml").write_text(yamlio.dump(defaults))
    (tmp_path / "templates/_helpers.tpl").write_text(
        dedent("""
        {{- define "guarded.encryption" -}}
        {{- if ne .Values.tls.mode "none" -}}true{{- end -}}
        {{- end -}}
        {{- define "guarded.tls" -}}
        {{- if and (include "guarded.encryption" .) (not .Values.tls.autoGenerated) (not .Values.tls.secret) -}}
        TLS requires a secret or auto-generated certificates.
        {{- end -}}
        {{- end -}}
        {{- define "guarded.validate" -}}
        {{- $messages := list -}}
        {{- $messages := append $messages (include "guarded.tls" .) -}}
        {{- $messages := without $messages "" -}}
        {{- $message := join "\\n" $messages -}}
        {{- if $message -}}{{- printf "VALUES VALIDATION: %s" $message | fail -}}{{- end -}}
        {{- end -}}
    """)
    )
    (tmp_path / "templates/config.yaml").write_text(
        dedent("""
        {{- include "guarded.validate" . }}
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{ required "name required" .Values.name | quote }}
        data:
          mode: {{ .Values.tls.mode | quote }}
    """)
    )
    return Chart(tmp_path, {"type": "object"}, defaults)


def test_ast_call_navigation_and_cassandra_requirement(guarded_chart: Chart) -> None:
    """
    Follow helper call nodes without treating messages and comments as function calls.

    Args:
        guarded_chart (Chart): Chart with a nested validation helper graph.

    Returns:
        None: Literal words do not become sinks; helper requirements include dependent values.
    """
    assert calls(expression('printf "%s" "fail required include"')) == {"printf"}
    assert calls(expression('include "guarded.validate" .')) == {"include", "include:guarded.validate"}
    nodes = lower("{{ if false }}dead{{ else if true }}live{{ else }}other{{ end }}")
    assert [node.text for node in walk(nodes) if node.kind == "if"] == ["false", "true"]
    contracts = Contracts.build(guarded_chart.path)
    values = {**guarded_chart.defaults, "tls": {"mode": "", "autoGenerated": False, "secret": ""}}
    rejection = contracts.predict(values)
    assert rejection is not None
    assert rejection.inputs == {"$.tls.mode": "", "$.tls.autoGenerated": False, "$.tls.secret": ""}
    assert "TLS requires" in rejection.message
    assert contracts.predict(guarded_chart.defaults) is None
    cassandra = Path(__file__).resolve().parents[3] / "third_party/bitnami-charts/bitnami/cassandra"
    if cassandra.is_dir():
        defaults = mapping(yamlio.load((cassandra / "values.yaml").read_text()))
        mapping(defaults["tls"])["internodeEncryption"] = ""
        observed = Contracts.build(cassandra).predict(defaults)
        assert observed is not None and "auto-generated certificates" in observed.message
        assert observed.inputs["$.tls.autoGenerated"] is False


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_native_rejection_and_dependent_generation(guarded_chart: Chart, tmp_path: Path) -> None:
    """
    Verify rejected-side witnesses and test a nearby accepted configuration with the target preserved.

    Args:
        guarded_chart (Chart): Native chart containing an explicit TLS contract.
        tmp_path (Path): Report destination.

    Returns:
        None: Filtered runs expose requirement evidence and keep accepted manifest checks active.
    """
    values = {**guarded_chart.defaults, "tls": {"mode": "", "autoGenerated": False, "secret": ""}}
    rejection = Contracts.build(guarded_chart.path).predict(values)
    assert rejection is not None
    with pytest.raises(RenderFailure) as failure:
        render(guarded_chart, values)
    assert matches_rejection(str(failure.value), rejection)
    ordinary = check_chart(guarded_chart, input_strategy=st.just(values), max_examples=1)
    assert ordinary["status"] == "failed"
    filtered = check_chart(
        guarded_chart, input_strategy=st.just(values), max_examples=1, filter_rejections=True, protected_paths=(("tls", "mode"),)
    )
    assert filtered["status"] == "passed", filtered
    evidence = mapping(filtered["configuration_rejections"])
    assert evidence["adjusted_candidates"] == 1
    assert evidence["verification_renders"] == 1
    assert filtered["attempts"] == 2  # baseline plus the accepted replacement; rejection probe is separate
    assert not filtered["coverage_complete"]
    md, _ = write_reports(
        {
            "directory": "charts",
            "started_epoch": 1,
            "elapsed_seconds": 1,
            "charts_discovered": 1,
            "counts": {"passed": 1},
            "settings": {},
            "charts": [filtered],
        },
        tmp_path / "report",
    )
    assert "Configuration rejections" in md.read_text()
    assert "TLS requires" in md.read_text()
    assert "$.tls.autoGenerated = false" in md.read_text()


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_unrepairable_rejections_are_not_passes(guarded_chart: Chart) -> None:
    """
    Exclude a fixed invalid candidate without counting its rejection as successful coverage.

    Args:
        guarded_chart (Chart): Chart whose selected TLS subtree cannot be changed.

    Returns:
        None: Empty accepted samples have an explicit nonpassing status and one verified witness.
    """
    values = {**guarded_chart.defaults, "tls": {"mode": "", "autoGenerated": False, "secret": ""}}
    report = check_chart(
        guarded_chart, input_strategy=st.just(values), max_examples=1, filter_rejections=True, protected_paths=(("tls",),), fail_fast=True
    )
    assert report["status"] == "configuration-rejected", report
    assert report["attempts"] == 1
    assert mapping(report["configuration_rejections"])["verification_renders"] == 1


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_required_zero_false_and_opaque_guards(guarded_chart: Chart) -> None:
    """
    Match Helm required semantics and retain ordinary errors behind unsupported conditions.

    Args:
        guarded_chart (Chart): Native chart with mutable isolated template text.

    Returns:
        None: Zero and false are accepted; dynamic guards remain ordinary failing attempts.
    """
    contracts = Contracts.build(guarded_chart.path)
    for value in (0, False):
        assert contracts.predict({**guarded_chart.defaults, "name": value}) is None
        render(guarded_chart, {"name": value})
    for empty_value in ("", None):
        assert contracts.predict({**guarded_chart.defaults, "name": empty_value}) is not None
    target = guarded_chart.path / "templates/config.yaml"
    target.write_text(
        dedent("""
        {{ if eq (tpl .Values.name .) "bad" }}{{ fail "dynamic rejection" }}{{ end }}
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: safe
    """)
    )
    report = check_chart(guarded_chart, input_strategy=st.just({"name": "bad"}), max_examples=1, filter_rejections=True)
    assert report["status"] == "failed"
    assert "dynamic rejection" in str(report["error"])
    assert mapping(report["configuration_rejections"])["filtered_candidates"] == 0


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_guard_filter_keeps_baseline_and_unexpected_render_errors(guarded_chart: Chart) -> None:
    """
    Keep supplied-default failures and earlier unrelated execution errors visible.

    Args:
        guarded_chart (Chart): Isolated chart with an understood TLS validation condition.

    Returns:
        None: Neither invalid defaults nor a different Helm error is silently classified as a configuration rejection.
    """
    values = {**guarded_chart.defaults, "tls": {"mode": "", "autoGenerated": False, "secret": ""}}
    invalid = Chart(guarded_chart.path, guarded_chart.schema, values)
    (guarded_chart.path / "values.yaml").write_text(yamlio.dump(values))
    result = check_chart(invalid, input_strategy=st.just(values), max_examples=1, filter_rejections=True)
    assert result["status"] == "failed"
    assert mapping(result["configuration_rejections"])["filtered_candidates"] == 0
    (guarded_chart.path / "values.yaml").write_text(yamlio.dump(guarded_chart.defaults))
    template = guarded_chart.path / "templates/config.yaml"
    original = template.read_text()
    template.write_text('{{ if ne .Values.tls.mode "none" }}{{ .Values.missing.parent }}{{ end }}\n' + original)
    result = check_chart(guarded_chart, input_strategy=st.just(values), max_examples=1, filter_rejections=True)
    assert result["status"] == "failed"
    assert "nil pointer" in str(result["error"])
    assert mapping(result["configuration_rejections"])["classifier_disagreements"] == 1
    assert mapping(result["configuration_rejections"])["filtered_candidates"] == 0
    template.write_text('{{ $_ := set .Values.tls "autoGenerated" true }}\n' + original)
    assert Contracts.build(guarded_chart.path).predict(values) is None


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_finite_filters_preserve_assignments_and_counters(guarded_chart: Chart) -> None:
    """
    Exclude rejected finite assignments without repairing them into different planned cases.

    Args:
        guarded_chart (Chart): Chart with a finite invalid-only override domain and valid defaults.

    Returns:
        None: The rejection is neither a pass nor remaining unattempted work.
    """
    invalid = {**guarded_chart.defaults, "tls": {"mode": "", "autoGenerated": False, "secret": ""}}
    guarded_chart.schema = {"enum": [guarded_chart.defaults, invalid]}
    result = check_chart(guarded_chart, exhaustive=True, filter_rejections=True)
    assert result["status"] == "configuration-rejected", result
    assert mapping(result["configuration_rejections"])["adjusted_candidates"] == 0
    assert mapping(result["configuration_rejections"])["filtered_candidates"] == 1
    assert result["remaining_iterations"] == 0
    assert result["unattempted_iterations"] == 0
    assert not result["coverage_complete"]
    (guarded_chart.path / "values.schema.json").write_text(json.dumps(guarded_chart.schema))
    conflict = check_chart(guarded_chart, exhaustive=True, filter_rejections=True)
    assert conflict["status"] == "failed", conflict
    assert mapping(conflict["configuration_rejections"])["schema_conflicts"] == 1
    assert mapping(conflict["configuration_rejections"])["filtered_candidates"] == 0


@pytest.mark.skipif(shutil.which("helm") is None, reason="requires Helm")
def test_actual_cassandra_validator_with_helm(guarded_chart: Chart) -> None:
    """
    Exercise Cassandra's retained helper source through Helm with a valid dependent-field replacement.

    Args:
        guarded_chart (Chart): Isolated chart shell receiving the actual Cassandra validator.

    Returns:
        None: The original TLS mode remains selected while auto-generation satisfies Cassandra's guard.
    """
    source = Path(__file__).resolve().parents[3] / "third_party/bitnami-charts/bitnami/cassandra"
    if not source.is_dir():
        pytest.skip("Cassandra source submodule is unavailable")
    defaults = mapping(yamlio.load((source / "values.yaml").read_text()))
    (guarded_chart.path / "values.yaml").write_text(yamlio.dump(defaults))
    shutil.copyfile(source / "templates/_helpers.tpl", guarded_chart.path / "templates/_helpers.tpl")
    (guarded_chart.path / "templates/config.yaml").write_text(
        dedent("""
        {{- include "cassandra.validateValues" . }}
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: validator-witness
        data:
          mode: {{ .Values.tls.internodeEncryption | quote }}
          generated: {{ .Values.tls.autoGenerated | quote }}
    """)
    )
    chart = Chart(guarded_chart.path, {"type": "object"}, defaults)
    tls = {**mapping(defaults["tls"]), "internodeEncryption": ""}
    observed: list[dict[str, object]] = []
    report = check_chart(
        chart,
        input_strategy=st.just({**defaults, "tls": tls}),
        max_examples=1,
        filter_rejections=True,
        protected_paths=(("tls", "internodeEncryption"),),
        properties=(lambda resources: observed.extend(resources),),
    )
    assert report["status"] == "passed", report
    assert observed[-1]["data"] == {"mode": "", "generated": "true"}
    rejection = mapping(report["configuration_rejections"])
    assert rejection["verification_renders"] == 1
    assert rejection["adjusted_candidates"] == 1
