apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  value: "{{ if .Values.input000 }}{{ if .Values.input001 }}1.150349{{ else }}-0.318639{{ end }}{{ else }}{{ if .Values.input001 }}0.318639{{ else }}-1.150349{{ end }}{{ end }}"
