{{ if .Values.input008 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-009-state
data:
  base: present
{{ if .Values.input008 }}{{ if .Values.input006 }}{{ if .Values.input009 }}{{ if .Values.input005 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-009-rare
data:
  region: rare
{{ end }}{{ end }}{{ end }}{{ end }}

{{ end }}
